$theme = ['à l\'antique ',
'c\'était demain '
, 'pas drôle mais beau '
, 'pauvre espèce humaine '
, 'jeu dans le jeu '
, 'poésie en image '
, 'en France profonde '
, 'du rire aux larmes (et retour) '
, 'docu '
, 'les chocottes à zéro '
, 'la parole est d\'or '
, 'Paris '
, 'culte ou my(s)tique '
, 'pour petits et grands enfants '
, 'en avant la musique '
, 'Los Angeles & Hollywood '
, 'cadavre(s) dans le(s) placard(s) '
, 'vive la (critique) sociale ! '
, 'épique pas toc '
, 'du Moyen-Age à 1914 '
, 'New-York '
, 'heurs et malheurs à deux '
, 'Bollywooderie '
, 'conte de fées relooké '
, 'entre Berlin et Moscou '
, 'portrait d\'époque (après 1914) '
, 'carrément à l\'ouest '
, 'vers le soleil levant '
, 'perle de nanard '  ];
